import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { BottomSheet } from "../BottomSheet";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [isBottomSheetOpen, setIsBottomSheetOpen] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button
          className={styles.button}
          onClick={() => setIsBottomSheetOpen(true)}
        >
          Open Modal
        </button>
        <BottomSheet
          open={isBottomSheetOpen}
          onClose={() => setIsBottomSheetOpen(false)}
        />
      </main>
    </div>
  );
};

export default Home;
